---
# Step-CA Vault Variables
# This file contains sensitive values that MUST be encrypted with ansible-vault
#
# To create an encrypted vault file:
#   ansible-vault create group_vars/all/vault.yml
#
# To edit an existing vault file:
#   ansible-vault edit group_vars/all/vault.yml
#
# Required variables:

# CA initialization password (minimum 16 characters)
# Generate a strong password: openssl rand -base64 24
vault_stepca_password: "CHANGE_ME_minimum_16_chars"
