---
galaxy_info:
  role_name: step_ca_docker
  author: tegge@Github
  description: Deploy Smallstep step-ca Certificate Authority in Docker
  company: ""
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

  galaxy_tags:
    - docker
    - certificates
    - pki
    - ca
    - stepca
    - smallstep
    - acme
    - tls
    - security

dependencies: []
